"""
niyah_executive.supervisor.state

Typed state schema for the Phalanx Shield LangGraph supervisor.
All fields are immutable between nodes; mutations return new state dicts.
"""

from __future__ import annotations

from enum import Enum, auto
from typing import Annotated, Any
import operator

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class ThreatClass(str, Enum):
    """Threat classification output from integrity_gate."""
    CLEAN            = "clean"
    UNICODE_SMUGGLER = "unicode_smuggler"   # hidden Unicode tag injection
    PROMPT_INJECTION = "prompt_injection"   # semantic subversion attempt
    ACTIVATION_STEER = "activation_steer"  # residual stream manipulation
    CONTRACT_VULN    = "contract_vuln"      # unchecked low-level call / DASP
    EXFIL_ATTEMPT    = "exfil_attempt"      # network exfiltration detected
    UNKNOWN          = "unknown"


class RouteDecision(str, Enum):
    """Supervisor routing decision."""
    INTEGRITY_GATE        = "integrity_gate"
    ACTIVATION_INSPECTOR  = "activation_inspector"
    STATIC_AUDITOR        = "static_auditor"
    TARPIT_CONTROLLER     = "tarpit_controller"
    PASS_THROUGH          = "pass_through"   # clean, forward to Lobe II
    HALT                  = "halt"           # unrecoverable threat, halt chain


class PhalanxState(dict):
    """
    Typed state container for the Phalanx Shield graph.

    Fields
    ------
    messages        : Accumulated message thread (add_messages reducer).
    raw_input       : Original, unsanitized input payload (bytes or str).
    sanitized_input : Output of integrity_gate sanitization.
    threat_class    : Classified threat type.
    threat_score    : Float [0.0, 1.0] — confidence of threat detection.
    route           : Current routing decision.
    audit_report    : Static auditor findings (list of Finding dicts).
    tarpit_rules    : BGP FlowSpec rules generated by tarpit_controller.
    metadata        : Trusted Metadata Envelope (set by integrity_gate).
    halt_reason     : Human-readable halt justification.
    """
    messages:         Annotated[list[BaseMessage], add_messages]
    raw_input:        str | bytes
    sanitized_input:  str
    threat_class:     ThreatClass
    threat_score:     float
    route:            RouteDecision
    audit_report:     list[dict[str, Any]]
    tarpit_rules:     list[dict[str, Any]]
    metadata:         dict[str, Any]
    halt_reason:      str


def initial_state(raw_input: str | bytes) -> dict:
    """Construct a clean initial PhalanxState."""
    return {
        "messages":        [],
        "raw_input":       raw_input,
        "sanitized_input": "",
        "threat_class":    ThreatClass.UNKNOWN,
        "threat_score":    0.0,
        "route":           RouteDecision.INTEGRITY_GATE,
        "audit_report":    [],
        "tarpit_rules":    [],
        "metadata":        {},
        "halt_reason":     "",
    }
