"""
niyah_executive.agents.tarpit_controller

Layer 4 — Network Egress Control: Sovereign Tarpit Generator

Responsibilities
────────────────
1. On detection of an exfiltration attempt (ThreatClass.EXFIL_ATTEMPT),
   generate BGP FlowSpec rules to rate-limit suspected exfiltration
   destinations to 0 bps.
2. Rules are emitted as structured dicts for consumption by the
   network control plane (e.g., GoBGP, BIRD2 FlowSpec speaker).
3. This module generates DEFENSIVE rules only — it does not initiate
   any outbound connections, does not perform port scanning, and
   does not generate offensive traffic.

BGP FlowSpec RFC 5575 / RFC 8955 rule format:
  { type: 5 (destination-prefix), value: "x.x.x.x/y" }
  { type: 12 (traffic-rate-bps), value: 0 }  ← rate-limit to 0 = drop

Design constraints
──────────────────
- No network I/O in this module. Rules are returned as data structures.
- Applying rules to a live BGP speaker is the responsibility of the
  network control plane operator — NOT this agent.
- IPv4 and IPv6 supported.
- Maximum 64 rules per invocation (BGP FlowSpec NLRI size limit).
"""

from __future__ import annotations

import ipaddress
import time
from typing import Any

from ..supervisor.state import ThreatClass


# BGP FlowSpec type codes (RFC 5575 §4)
FS_TYPE_DST_PREFIX   = 1
FS_TYPE_SRC_PREFIX   = 2
FS_TYPE_IP_PROTO     = 3
FS_TYPE_TRAFFIC_RATE = 12  # Extended community: rate in bytes/s (0 = drop)

MAX_RULES = 64


class TarpitController:
    """
    BGP FlowSpec rule generator for exfiltration interdiction.

    Input:  state["metadata"]["exfil_destinations"] — list of IP/CIDR strings
            detected by upstream anomaly detection.
    Output: state["tarpit_rules"] — list of FlowSpec rule dicts.
    """

    def run(self, state: dict) -> dict:
        metadata = state.get("metadata", {})
        destinations: list[str] = metadata.get("exfil_destinations", [])

        if not destinations:
            # Attempt to extract from threat metadata if available
            destinations = self._extract_from_context(state)

        rules: list[dict[str, Any]] = []

        for dest in destinations[:MAX_RULES]:
            prefix = self._normalize_prefix(dest)
            if prefix is None:
                continue
            rule = self._build_flowspec_rule(prefix)
            rules.append(rule)

        updated_meta = {
            **metadata,
            "tarpit_generated_at": time.time(),
            "tarpit_rule_count":   len(rules),
        }

        return {
            **state,
            "tarpit_rules": rules,
            "metadata":     updated_meta,
            "halt_reason":  (
                f"Exfiltration attempt detected. "
                f"{len(rules)} FlowSpec rule(s) generated for operator deployment."
            ),
        }

    # ── Helpers ──────────────────────────────────────────────────────────────

    @staticmethod
    def _normalize_prefix(dest: str) -> str | None:
        """Normalize a raw IP or CIDR string. Returns None if invalid."""
        dest = dest.strip()
        try:
            # Strict=False: host bits are masked (e.g. 10.0.0.1/24 → 10.0.0.0/24)
            net = ipaddress.ip_network(dest, strict=False)
            return str(net)
        except ValueError:
            return None

    @staticmethod
    def _build_flowspec_rule(prefix: str) -> dict[str, Any]:
        """Build a BGP FlowSpec NLRI rule dict for rate-limit-to-zero."""
        return {
            "nlri": [
                {"type": FS_TYPE_DST_PREFIX, "value": prefix},
                {"type": FS_TYPE_TRAFFIC_RATE, "value": 0},  # drop
            ],
            "action":    "rate-limit",
            "rate_bps":  0,
            "prefix":    prefix,
            "comment":   "Sovereign Tarpit — auto-generated by Phalanx Shield",
            "apply_via": "OPERATOR_MANUAL",  # must be applied by human operator
        }

    @staticmethod
    def _extract_from_context(state: dict) -> list[str]:
        """
        Attempt to extract destination IPs from sanitized input
        (last-resort heuristic for plaintext exfil indicators).
        """
        import re
        text = state.get("sanitized_input", "")
        ipv4_re = re.compile(
            r"\b(?:\d{1,3}\.){3}\d{1,3}(?:/\d{1,2})?\b"
        )
        return ipv4_re.findall(text)[:MAX_RULES]
